config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :posts do
    resources :comments, :except => [:show, :index]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_name, :presence => true
  validates :description, :presence => true

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :video_url, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true

  has_many :comments


  def self.Search(searchString)
    result = self.basic_search(title: searchString)
    if result.kind_of?(Array)
      return result
    else
      return []
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "You have commented, congrats!"
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:description, :user_name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @results = Post.search(params[:criteria])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    videoId = post_params[:video_url].split("=")[1]
    title = post_params[:title]
    description = post_params[:description]
    @post = Post.new(video_url: videoId, title: title, description: description)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end


  private
  def post_params
    params.require(:post).permit(:video_url, :title, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1 id="do-styles">Featured Lip Syncs of the week!</h1><br>

<div class="container-fluid">
  <div class="span8">
  <div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class=""></li>
      <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="2" class=""></li>
    </ol>
    <div class="carousel-inner">
      <div class="item active">
        <iframe width="100%" height="500px" src="https://www.youtube.com/embed/aKdV5FvXLuI" frameborder="0" allowfullscreen=""></iframe>
      </div>
      <div class="item">
        <iframe width="100%" height="500px" src="https://www.youtube.com/embed/WYetZzlVOLI" frameborder="0" allowfullscreen=""></iframe>
      </div>
      <div class="item">
        <iframe width="100%" height="500px" src="https://www.youtube.com/embed/TipIEzIl7wY" frameborder="0" allowfullscreen=""></iframe>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
  </div>
</div>

app/views/layouts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :video_url %>
  <%= f.text_field :video_url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/_searched.html.erb
<h3>Search Results</h3>
<ul>
  <% @results.each do |result| %>
    <li><%= link_to result.title, post_path(result) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LipSyncFanz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-static-top navbar-inverse">
    <div class="navbar-inner">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/posts">View All Lip-Sync Battles</a></li>
          <li><a href="/posts/new">Post some LINX</a></li>
        </ul>

        <ul class="nav navbar-nav pull-right">
          <li class="search"><%= form_tag("/posts", method: "get") do %>
            <%= text_field_tag(:criteria, nil, :placeholder => 'Search') %>
            <%= submit_tag("Search") %>
          <% end %></li>
        </ul>
    </div>
  </header>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>



<div class="col-sm-8">
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>
</div>

<div class="col-sm-4">
<% if @results.any? %>
  <h3>Search Results</h3>
  <ul>
    <% @results.each do |result| %>
      <li><%= link_to result.title, post_path(result) %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Show me the vidya!</h1>

<%= render "layouts/form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.video_url %>"  frameborder="0" allowfullscreen></iframe>

<div class="container">
  <h3>Comments</h3>
  <% @post.comments.each do |comment| %>
    <li><%= comment.description %> By: <%= comment.user_name %></li>
  <% end %>
</div>
  <%= link_to "Add a Comment", new_post_comment_path(@post) %>